create extension if not exists pgcrypto with schema extensions;
create extension if not exists pgtap with schema extensions;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  invite_code text default substr(md5(random()::text), 0, 8),
  status text default 'offline',
  current_task text,
  last_active_at timestamptz default now(),
  is_task_public boolean default true,
  email text,
  role text default 'user',
  created_at timestamptz default now(),
  nickname text,
  study_start_time timestamptz,
  total_stopwatch_time bigint default 0,
  timer_type text,
  timer_mode text,
  timer_duration integer
);

create table public.friendships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  friend_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  nickname text,
  group_name text,
  friend_email text,
  is_notification_enabled boolean default true
);

create table public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  sender_email text not null,
  receiver_email text,
  status text not null default 'pending',
  created_at timestamptz default now()
);

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  leader_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz default now()
);

create table public.group_members (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz default now(),
  nickname text,
  unique (group_id, user_id)
);

create table public.study_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  duration bigint,
  mode text,
  user_id uuid references auth.users(id) on delete cascade,
  task text,
  task_id uuid,
  group_id uuid references public.groups(id) on delete set null
);

create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  keys jsonb not null,
  created_at timestamptz not null default now()
);

create table public.feedbacks (
  id uuid primary key default gen_random_uuid(),
  content text not null,
  status text not null default 'pending'
    check (status in ('pending', 'reviewed', 'implemented')),
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  images text[] default array[]::text[],
  category text default 'other'
    check (category in ('bug', 'feature', 'other'))
);

create table public.feedback_replies (
  id uuid primary key default gen_random_uuid(),
  feedback_id uuid not null references public.feedbacks(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  content text not null,
  created_at timestamptz not null default now(),
  images text[] default array[]::text[]
);

create table public.debug_logs (
  id bigint generated by default as identity primary key,
  message text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.friend_requests enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.study_sessions enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.feedbacks enable row level security;
alter table public.feedback_replies enable row level security;
alter table public.debug_logs enable row level security;

create policy "Allow insert for everyone"
on public.debug_logs for insert to public
with check (true);

create policy "Allow select for everyone"
on public.debug_logs for select to public
using (true);

create policy "Enable insert for authenticated users only"
on public.debug_logs for insert to authenticated
with check (true);

create policy "Enable select for users based on user_id"
on public.debug_logs for select to authenticated
using (true);

create policy "Users can view own profile"
on public.profiles for select to authenticated
using (auth.uid() = id);

create policy "Users can update own profile."
on public.profiles for update to public
using (auth.uid() = id);

create policy "Users can view requests sent by them or to them"
on public.friend_requests for select to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- Pre-remediation production policies. These reproduce the attackable state that
-- the friend_requests DML lockdown migration must close:
--   * INSERT gated only on the caller being the sender (self-requests allowed).
--   * UPDATE gated only on receiver ownership with NO `with check`, so a receiver
--     can rewrite identity columns (sender_id / sender_email / status).
create policy "Users can create requests"
on public.friend_requests for insert to authenticated
with check (auth.uid() = sender_id);

create policy "Users can update requests received by them"
on public.friend_requests for update to authenticated
using (auth.uid() = receiver_id);

create policy "Users can see their own friendships."
on public.friendships for select to authenticated
using (auth.uid() = user_id or auth.uid() = friend_id);

create policy "Users can insert their own subscriptions"
on public.push_subscriptions for insert to authenticated
with check (auth.uid() = user_id);

create policy "Users can view their own subscriptions"
on public.push_subscriptions for select to authenticated
using (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
on public.push_subscriptions for delete to authenticated
using (auth.uid() = user_id);

create policy "Authenticated users can view all feedbacks"
on public.feedbacks for select to authenticated
using (true);

create policy "Users can create feedback"
on public.feedbacks for insert to authenticated
with check (true);

create policy "Users can delete their own feedbacks"
on public.feedbacks for delete to authenticated
using (auth.uid() = user_id);

create policy "Admins can delete feedbacks"
on public.feedbacks for delete to authenticated
using (
  exists (
    select 1
    from public.profiles as p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

create policy "Authors can update their pending feedbacks"
on public.feedbacks for update to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

create policy "Admins can update feedbacks"
on public.feedbacks for update to authenticated
using (
  exists (
    select 1
    from public.profiles as p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles as p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

create policy "Authenticated users can view all replies"
on public.feedback_replies for select to authenticated
using (true);

create policy "Authenticated users can insert replies"
on public.feedback_replies for insert to authenticated
with check (true);

create policy "Users can delete their own replies"
on public.feedback_replies for delete to authenticated
using (auth.uid() = user_id);

create policy "Admins can delete any reply"
on public.feedback_replies for delete to authenticated
using (
  exists (
    select 1
    from public.profiles as p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

create function public.delete_unconfirmed_users()
returns void
language plpgsql
security definer
as $$
begin
  delete from auth.users
  where email_confirmed_at is null
    and created_at < now() - interval '3 minutes';
end;
$$;

create function public.add_friend(p_friend_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.friendships (user_id, friend_id)
  values (auth.uid(), p_friend_id);
end;
$$;

create function public.get_user_id_by_email(email_input text)
returns uuid
language sql
security definer
as $$
  select id from auth.users where lower(email) = lower(email_input) limit 1;
$$;

create function public.get_group_study_time(p_group_id uuid, p_date text)
returns table (user_id uuid, total_seconds integer)
language sql
security definer
as $$
  select null::uuid, 0::integer where false;
$$;

create function public.get_group_study_time_v2(p_date text, p_group_id uuid)
returns table (user_id uuid, total_seconds integer)
language sql
security definer
as $$
  select null::uuid, 0::integer where false;
$$;

grant execute on all functions in schema public to public, anon, authenticated, service_role;
